using DBAccessLib.Core.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Util
{
    public class Book
    {
        public int Id { get; set; }  // Auto-generated by the database
        [ColumnName("BookName")]
        public string MyBookNameInEnglish { get; set; }

        public long AuthorId { get; set; }

        public long PublisherId { get; set; }

        public string ISBN10 { get; set; }

        public string ISBN13 { get; set; }

        public string CoverLink { get; set; }

        public string BackCoverLink { get; set; }

        public string BookLanguage { get; set; }

        public DateTime PublicationDate { get; set; }

        public int NumberOfPages { get; set; }

        public decimal? CostPrice { get; set; } // Nullable

        public decimal? RentPrice { get; set; } // Nullable

        public string BookDescription { get; set; }

        public string BookBinding { get; set; }

        public decimal BookWeight { get; set; }

        public DateTime CreatedAt { get; set; }

        public DateTime UpdatedAt { get; set; }
    }

}
